print('======Registrador de Datas de Nascimento======')
dia=input('Digite o dia: ')
mes=input('Digite o mês: ')
ano=input('Digite o ano: ')
print('Você nasceu no dia', dia,'/', mes,'/', ano, 'correto?')